name: diabetes_app
description: "A cross-platform diabetes management app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  google_fonts: ^6.3.2
  curved_navigation_bar: ^1.0.6
  fl_chart: ^1.1.1
  awesome_snackbar_content: ^0.1.8
  introduction_screen: ^4.0.0
  cached_network_image: ^3.4.0
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  
  http: ^1.2.1
  camera: ^0.11.3
  google_mlkit_barcode_scanning: ^0.12.0
  
  # Health Connect
  health: ^13.2.0
  permission_handler: ^11.3.1
  intl: ^0.20.2
  
  # Secure Storage for Dexcom credentials
  flutter_secure_storage: ^9.2.2

  # Local saving of foods
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_diabeto.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo_diabeto.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo_diabeto.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo_diabeto.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
