name: diabetes_app
description: "A cross-platform diabetes management app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_fonts: ^6.3.2
  curved_navigation_bar: ^1.0.6
  fl_chart: ^1.1.1
  awesome_snackbar_content: ^0.1.8
  introduction_screen: ^4.0.0
  cached_network_image: ^3.4.0
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  
  # Upgrading back to latest stable versions now that configuration is fixed
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.0
  
  http: ^1.2.1
  camera: ^0.10.5
  google_mlkit_barcode_scanning: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/diabetes_logo_placeholder.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/diabetes_logo_placeholder.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/diabetes_logo_placeholder.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/diabetes_logo_placeholder.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
